Format with Prettier
betagouv/SPPNautInterface pull request #150
Opened 2023-02-26 17:53 UTC by rik

- Add Prettier config and ignore
- Check in CI
- Reformat files that are not matching our style

2023-02-26 21:04 UTC, fabienheureux requested changes
Une petite typo et une question 🙃

2023-02-26 21:04 UTC, fabienheureux commented on .gitignore
> +# https://github.com/prettier/prettier/issues/8048Contenu_du_mac
```suggestion
# https://github.com/prettier/prettier/issues/8048
Contenu_du_mac
```

Petite typo

2023-02-26 21:04 UTC, fabienheureux commented on package.json
> +        "lint": "prettier --check ."
Question : veut-on inclure les fichiers html aux check prettier ? D'expérience il s'accorde pas très bien avec les tags django

2023-02-27 08:35 UTC, rik commented on .gitignore
> +# https://github.com/prettier/prettier/issues/8048Contenu_du_mac
Autant enlever cet ignore qui ne servait qu'à moi :)

2023-02-27 08:37 UTC, rik commented on package.json
> +        "lint": "prettier --check ."
Non on ne veut pas les vérifier et c'est pour ça qu'ils sont dans `.prettierignore`.

2023-02-27 08:38 UTC, fabienheureux commented on package.json
> +        "lint": "prettier --check ."
En effet 😅

2023-02-27 08:39 UTC, fabienheureux approved these changes

2023-02-27 08:40 UTC, merged